version: "2"
services:

  nginx_dockstore:
    build:
      context: .
      dockerfile: config/Dockerfile
    restart: always
    ports:
      - "8080:4200"
    volumes:
      - ./config/default.nginx_http.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/default.nginx_http.shared.conf:/etc/nginx/conf.d/default.nginx_http.shared.conf:ro
      - ./config/default.nginx_http.security.conf:/etc/nginx/conf.d/default.nginx_http.security.conf:ro
      - ./pages:/usr/share/nginx/html2
      - ./etc/ssl:/etc/ssl
    ### logging:
    ###   driver: "awslogs"
    ###   options:
    ###     awslogs-group: ${LOG_GROUP_NAME}
    ###     awslogs-stream: "nginx_dockstore"


